<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-07-13T07:15:59+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'UTC',
];
