<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-07-19T05:45:04+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      seo.url_rewriting
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'ja_JP',
    'version_installed' => '9.2.0',
    'version_db_installed' => '20230308163514',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1689232559,
        'latest_version' => '9.2.1',
    ],
    'email' => [
        'default' => [
            'address' => 'a@a.a.a',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
    'seo' => [
        'redirect_to_canonical_url' => false,
        'url_rewriting' => true,
    ],
];
