<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2023-07-19T05:45:04+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.canonical_tag.enabled
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'concretecmsで鹿',
            'timezone' => 'Asia/Tokyo',
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => false,
                ],
            ],
        ],
    ],
];
